/**
 * Danh sách các video CHƯA được viết thành bài công thức chi tiết trên
 * "/cong-thuc" — dùng làm hàng chờ để soạn tiếp các đợt công thức sau, lấy
 * đúng videoId + tiêu đề thật từ dữ liệu YouTube Studio Analytics (không
 * cần quét lại kênh). Sắp xếp theo lượt xem giảm dần — ưu tiên soạn các
 * video có lượt xem cao trước vì khả năng là chủ đề được nhiều người quan
 * tâm tìm kiếm.
 *
 * Quy trình dùng: chọn 1 video ở đây → nhờ Claude soạn công thức đầy đủ
 * (nguyên liệu, các bước, mẹo nhỏ) dựa trên tên món trong tiêu đề → thêm
 * vào mảng `recipes` trong lib/recipes.ts với published: false → duyệt →
 * đổi published: true → xoá dòng tương ứng khỏi file này (không bắt buộc,
 * chỉ để tránh trùng lặp khi chọn video cho đợt sau).
 *
 * Một số video có title rỗng (không có tiêu đề rõ ràng trong dữ liệu xuất
 * ra từ YouTube Studio) — nên mở video thật trên YouTube để xem tên món
 * trước khi soạn công thức cho các mục này.
 */

export type BacklogVideo = {
  videoId: string;
  title: string;
  slug: string;
};

export const videoBacklog: BacklogVideo[] = [
  { videoId: "uMZik6GxM9c", title: "Kết hợp đồ ăn thế nào để dáng đẹp, da xinh", slug: "ket-hop-do-an-the-nao-de-dang-dep-da-xinh" },
  { videoId: "hMvuNfrMV7o", title: "Tôi cứ nghĩ ăn dâu tây với muối xí muội là đỉnh cho đến khi biết cách ăn này", slug: "toi-cu-nghi-an-dau-tay-voi-muoi-xi-muoi-la-dinh-cho-den-khi-biet-cach" },
  { videoId: "XlfWAoRMLSI", title: "xlfwaormlsi", slug: "xlfwaormlsi" },
  { videoId: "NwYMjLh09bI", title: "Tự làm bánh canh cá lóc từ a đến z", slug: "tu-lam-banh-canh-ca-loc-tu-a-den-z" },
  { videoId: "sK6DsuilZ8o", title: "sk6dsuilz8o", slug: "sk6dsuilz8o" },
  { videoId: "SGfA4R0UjBg", title: "Bí mật cách nêm món bún gà nấm không phải ai cũng biết", slug: "bi-mat-cach-nem-mon-bun-ga-nam-khong-phai-ai-cung-biet" },
  { videoId: "tI_UD1ku0ao", title: "Thử làm ba chỉ cuộn khoai tây, ăn cực cuốn luôn", slug: "thu-lam-ba-chi-cuon-khoai-tay-an-cuc-cuon-luon" },
  { videoId: "Z85rswnbxK4", title: "Bí quyết làm Chả ốc giòn dai, không bị bở bằng giấy bạc | Góc Bếp", slug: "bi-quyet-lam-cha-oc-gion-dai-khong-bi-bo-bang-giay-bac-goc-bep" },
  { videoId: "YVWO5vnAkyA", title: "Bí quyết làm chả cốm đơn giản, ngon chuẩn vị", slug: "bi-quyet-lam-cha-com-don-gian-ngon-chuan-vi" },
  { videoId: "9hVR3oWGd-o", title: "Cơm nhà 3 món ngon khó cưỡng! 🏡🍚✨", slug: "com-nha-3-mon-ngon-kho-cuong" },
  { videoId: "09bRbUNghLQ", title: "Bí quyết làm món bao tử hấp tiêu xanh không bị hôi, giòn sần sật", slug: "bi-quyet-lam-mon-bao-tu-hap-tieu-xanh-khong-bi-hoi-gion-san-sat" },
  { videoId: "4g5wPa-VPRw", title: "Cách người Hoa làm Thịt kho tàu", slug: "cach-nguoi-hoa-lam-thit-kho-tau" },
  { videoId: "oyjqCJNQa5Y", title: "Đuôi heo chiên giòn món này lai rai thì nhức nách", slug: "duoi-heo-chien-gion-mon-nay-lai-rai-thi-nhuc-nach" },
  { videoId: "yOMFltMmzl8", title: "Bún thang có xứng đáng xếp vào hàng tinh hoa ẩm thực không?", slug: "bun-thang-co-xung-dang-xep-vao-hang-tinh-hoa-am-thuc-khong" },
  { videoId: "gCR7LxgALIE", title: "Nem cá rán, đổi vị cho cả nhà", slug: "nem-ca-ran-doi-vi-cho-ca-nha" },
  { videoId: "kZXAakQyIX8", title: "Bí quyết làm chân gà sốt thái, chua chua cay cay, lai rai thêm vài ly nữa là hết ý", slug: "bi-quyet-lam-chan-ga-sot-thai-chua-chua-cay-cay-lai-rai-them-vai-ly-nu" },
  { videoId: "kzt0SHhKXBw", title: "Trứng ngâm tương lòng đào mát lạnh, đưa cơm 🥚❄️", slug: "trung-ngam-tuong-long-dao-mat-lanh-dua-com" },
  { videoId: "x3s0eugR9jo", title: "Sườn kho nước có ga: Bí quyết thịt mềm tan, màu cực đẹp không cần nước hàng 🥤🍖", slug: "suon-kho-nuoc-co-ga-bi-quyet-thit-mem-tan-mau-cuc-dep-khong-can-nuoc-h" },
  { videoId: "bH_cvD5A2n4", title: "Bún riêu cua rất ngon lại còn dễ làm", slug: "bun-rieu-cua-rat-ngon-lai-con-de-lam" },
  { videoId: "-IpajaIkflY", title: "Biết được cách làm này, tiệm cơm gà xối mỡ chắc ế khách luôn", slug: "biet-duoc-cach-lam-nay-tiem-com-ga-xoi-mo-chac-e-khach-luon" },
  { videoId: "CJPMrVSATgw", title: "Canh mọc chua chua thanh thanh cho ngày hè gay gắt", slug: "canh-moc-chua-chua-thanh-thanh-cho-ngay-he-gay-gat" },
  { videoId: "krcAm349c6U", title: "Đùi gà sốt CocaCola ngon đậm đà", slug: "dui-ga-sot-cocacola-ngon-dam-da" },
  { videoId: "_4hphAdF1DQ", title: "Chi tiết công thức làm bánh ít trần, bất ngờ hơn khi luộc lại ngon hơn hấp", slug: "chi-tiet-cong-thuc-lam-banh-it-tran-bat-ngo-hon-khi-luoc-lai-ngon-hon" },
  { videoId: "CuCgEI3pwNk", title: "Cơm nguội ăn không hết thì thử làm bánh cuốn đi, càng cuốn lại càng cuốn", slug: "com-nguoi-an-khong-het-thi-thu-lam-banh-cuon-di-cang-cuon-lai-cang-cuo" },
  { videoId: "q8Me8OsA7ZY", title: "Gà hấp ngải cứu là xưa rồi, giờ tui làm cá hấp ngải cứu cho lạ nè", slug: "ga-hap-ngai-cuu-la-xua-roi-gio-tui-lam-ca-hap-ngai-cuu-cho-la-ne" },
  { videoId: "TGbuN_5ZNZM", title: "Bánh tẻ, món bánh đợi mẹ đi chợ về của tuổi thơ tôi", slug: "banh-te-mon-banh-doi-me-di-cho-ve-cua-tuoi-tho-toi" },
  { videoId: "PWbtoMGhRjw", title: "Bún Thái Hải Sản, người mê người chê, còn bạn thì sao?", slug: "bun-thai-hai-san-nguoi-me-nguoi-che-con-ban-thi-sao" },
  { videoId: "ZaaQ6HrTWFQ", title: "Bánh tráng nướng làm chơi mà ngon thiệt", slug: "banh-trang-nuong-lam-choi-ma-ngon-thiet" },
  { videoId: "jj3K3p5rkIk", title: "Không cần phải ra Nha Trang để ăn nem lụi", slug: "khong-can-phai-ra-nha-trang-de-an-nem-lui" },
  { videoId: "OtNfMj02oBE", title: "Cá nổ muối, ngọt khó tả", slug: "ca-no-muoi-ngot-kho-ta" },
  { videoId: "HPKfVUubwGo", title: "Thịt kho bằng nồi cơm điện của team lười", slug: "thit-kho-bang-noi-com-dien-cua-team-luoi" },
  { videoId: "7yQ2dwpGvJw", title: "Trứng cút rim lạp xường làm thêm miếng dưa hấu nữa thì nhức nách", slug: "trung-cut-rim-lap-xuong-lam-them-mieng-dua-hau-nua-thi-nhuc-nach" },
  { videoId: "DXRfREXTKyw", title: "Món này thơm quá, hàng xóm kiện luôn", slug: "mon-nay-thom-qua-hang-xom-kien-luon" },
  { videoId: "Z2cqlRWwjgg", title: "Cá mè kho sung: Bí quyết cá chắc thịt, không tanh, thơm mùi quê cũ 🐟🌿", slug: "ca-me-kho-sung-bi-quyet-ca-chac-thit-khong-tanh-thom-mui-que-cu" },
  { videoId: "t5WREqy6hCo", title: "Bí quyết làm Mì Trộn Muối Ớt ai ăn cũng khen ngon", slug: "bi-quyet-lam-mi-tron-muoi-ot-ai-an-cung-khen-ngon" },
  { videoId: "RVzH91LyjEE", title: "Bún Riêu Cua Chuẩn Vị Bắc Khác Gì Miền Nam? 🦀", slug: "bun-rieu-cua-chuan-vi-bac-khac-gi-mien-nam" },
  { videoId: "QCl8R00hCKY", title: "qcl8r00hcky", slug: "qcl8r00hcky" },
  { videoId: "YbAx00CECgs", title: "Cá nục kho măng, món dân dã nhưng lại rất đưa cơm", slug: "ca-nuc-kho-mang-mon-dan-da-nhung-lai-rat-dua-com" },
  { videoId: "HyX7iRsu4Sk", title: "Bún Thái Hải Sản, chua chua, nhẹ nhàng", slug: "bun-thai-hai-san-chua-chua-nhe-nhang" },
  { videoId: "YQXNSyDDSss", title: "Bí quyết làm há cảo không cần làm vỏ", slug: "bi-quyet-lam-ha-cao-khong-can-lam-vo" },
  { videoId: "BupRO_oYDds", title: "BÚN CÁ NGỪ Nấu sao để không bị tanh?", slug: "bun-ca-ngu-nau-sao-de-khong-bi-tanh" },
  { videoId: "X_xvH4q8-A4", title: "Bạn đã thử món chả cá lá lốt chưa?", slug: "ban-da-thu-mon-cha-ca-la-lot-chua" },
  { videoId: "UZB1fNB3xY0", title: "Bí quyết luộc gà da vàng dong không phải ai cũng biết", slug: "bi-quyet-luoc-ga-da-vang-dong-khong-phai-ai-cung-biet" },
  { videoId: "3y4Dz3oKv6A", title: "Bún vét tủ lạnh, nấu trong 2 phút", slug: "bun-vet-tu-lanh-nau-trong-2-phut" },
  { videoId: "ogLfAmI-q2g", title: "Nui bò viên là một trong những món thích nhất của mình", slug: "nui-bo-vien-la-mot-trong-nhung-mon-thich-nhat-cua-minh" },
  { videoId: "aGeZ-oPbpd4", title: "cánh gà chiên giòn, lớn nhỏ đều mê", slug: "canh-ga-chien-gion-lon-nho-deu-me" },
  { videoId: "-rjzpSR4Gb4", title: "Trời ơi, ăn mây, tan mềm, quá đã", slug: "troi-oi-an-may-tan-mem-qua-da" },
  { videoId: "xxzqGVHT7Co", title: "Canh đuôi heo hầm đậu nành món cực kỳ bổ dưỡng", slug: "canh-duoi-heo-ham-dau-nanh-mon-cuc-ky-bo-duong" },
  { videoId: "ShJSUpOVhFk", title: "Bún măng vịt, nấu sao không bị hôi?", slug: "bun-mang-vit-nau-sao-khong-bi-hoi" },
  { videoId: "UIRcIzBeeuE", title: "Chim cút chiên bơ đơn giản, làm tại nhà cho an toàn", slug: "chim-cut-chien-bo-don-gian-lam-tai-nha-cho-an-toan" },
  { videoId: "Xq-jQiYWsUs", title: "Làm bánh đúc từ cơm nguội, mà cứ phải cơm nguội mới ngon", slug: "lam-banh-duc-tu-com-nguoi-ma-cu-phai-com-nguoi-moi-ngon" },
  { videoId: "40d_ML-s-64", title: "Gà bó xôi phiên bản mini cho bạn nhỏ ăn sáng", slug: "ga-bo-xoi-phien-ban-mini-cho-ban-nho-an-sang" },
  { videoId: "c0Bg0HM9Hv4", title: "Bí quyết Cánh gà chiên nước mắm: Da giòn tan, sốt óng ả chuẩn vị \"Góc Bếp\" 🍗✨", slug: "bi-quyet-canh-ga-chien-nuoc-mam-da-gion-tan-sot-ong-a-chuan-vi-goc-bep" },
  { videoId: "Ny1kWyVrYcc", title: "ny1kwyvrycc", slug: "ny1kwyvrycc" },
  { videoId: "_bvECkuICKs", title: "Cách nấu súp hoành thánh của người Nhật, thanh đạm, đổi vị cho ngày mệt mỏi", slug: "cach-nau-sup-hoanh-thanh-cua-nguoi-nhat-thanh-dam-doi-vi-cho-ngay-met" },
  { videoId: "FZgoi29jc7k", title: "Bún Cá Rô, món ăn mà không biết ăn gì thì tôi sẽ nấu", slug: "bun-ca-ro-mon-an-ma-khong-biet-an-gi-thi-toi-se-nau" },
  { videoId: "NslVL52PKM4", title: "Mì gà tầng ngải cứu phiên bản cho hết vào nồi", slug: "mi-ga-tang-ngai-cuu-phien-ban-cho-het-vao-noi" },
  { videoId: "LpIZRcjZk0w", title: "Ăn no món thấp calo, nấu trong 5 phút", slug: "an-no-mon-thap-calo-nau-trong-5-phut" },
  { videoId: "pOUTgQ88_3w", title: "Phở Cuốn Heo Quay | Giòn Rụm Mùi Vị Cứ Ngỡ Đâu Quê Nhà", slug: "pho-cuon-heo-quay-gion-rum-mui-vi-cu-ngo-dau-que-nha" },
  { videoId: "XkOcL_uM0HU", title: "BÚN ỐC OM CHUỐI ĐẬU | Vietnamese Noodle Snails with Banana? Surprisingly Good!", slug: "bun-oc-om-chuoi-dau-vietnamese-noodle-snails-with-banana-surprisingly" },
  { videoId: "wWVg7RI0xh0", title: "Tuyệt chiêu xử lý đầu cá hồi nấu cải chua béo mà không ngấy", slug: "tuyet-chieu-xu-ly-dau-ca-hoi-nau-cai-chua-beo-ma-khong-ngay" },
  { videoId: "Jgp-s8kPAwY", title: "Ếch nấu mẻ, món chân truyền của Bà tôi", slug: "ech-nau-me-mon-chan-truyen-cua-ba-toi" },
  { videoId: "twRqbxgmJl8", title: "Nộm sứa món nộm dễ nhất mà mình từng làm", slug: "nom-sua-mon-nom-de-nhat-ma-minh-tung-lam" },
  { videoId: "xW0sXC7057g", title: "Mang hương vị đồng quê về phố với món Ốc Bươu Nấu Chuối Đậu đậm đà", slug: "mang-huong-vi-dong-que-ve-pho-voi-mon-oc-buou-nau-chuoi-dau-dam-da" },
  { videoId: "904ZasrrUnU", title: "Món \"Quốc Thực\" nhưng không phải ai cũng biết làm", slug: "mon-quoc-thuc-nhung-khong-phai-ai-cung-biet-lam" },
  { videoId: "yxhwfMo-cTE", title: "Tự làm bánh tráng trộn tại nhà, ngon lại an toàn", slug: "tu-lam-banh-trang-tron-tai-nha-ngon-lai-an-toan" },
  { videoId: "9FpjtyYYyB4", title: "BÚN MẮM miền Tây, Đậm đà khó quên", slug: "bun-mam-mien-tay-dam-da-kho-quen" },
  { videoId: "r9KBBFi4Zqg", title: "Không ăn được mắm tôm và lá mơ, thì đừng coi video này nha", slug: "khong-an-duoc-mam-tom-va-la-mo-thi-dung-coi-video-nay-nha" },
  { videoId: "YFi23akcsaA", title: "Cơm nhà, nấu sao đủ chất lại nhanh?", slug: "com-nha-nau-sao-du-chat-lai-nhanh" },
  { videoId: "zs4C8YLbHhg", title: "Bún đậu mắm tôm cứ dăm bữa là lại thèm", slug: "bun-dau-mam-tom-cu-dam-bua-la-lai-them" },
  { videoId: "SMaJsOyT-1c", title: "Chuẩn công thức Cơm Gà Hội An từ người con xứ Quảng", slug: "chuan-cong-thuc-com-ga-hoi-an-tu-nguoi-con-xu-quang" },
  { videoId: "1D-Kq42pLI0", title: "Gà rán Hàn Quốc với ba vị sốt hấp dẫn đảm bảo lớn bé đều mê tít", slug: "ga-ran-han-quoc-voi-ba-vi-sot-hap-dan-dam-bao-lon-be-deu-me-tit" },
  { videoId: "OzswUde1fLE", title: "Cá diêu hồng chiên giòn mắm me: Đã miệng với tiếng \"rắc rắc\" ngay miếng đầu tiên", slug: "ca-dieu-hong-chien-gion-mam-me-da-mieng-voi-tieng-rac-rac-ngay-mieng-d" },
  { videoId: "AIqV68iq-ZE", title: "Bún Mọc Sườn Chua", slug: "bun-moc-suon-chua" },
  { videoId: "eYmcnnvTSf4", title: "BÚN giả cầy các bác ơi", slug: "bun-gia-cay-cac-bac-oi" },
  { videoId: "jTwHfNN0-FA", title: "Cá hồi nướng sốt trứng tự làm, ăn cơm cực kỳ hợp luôn", slug: "ca-hoi-nuong-sot-trung-tu-lam-an-com-cuc-ky-hop-luon" },
  { videoId: "QVs6aKgg_ow", title: "Bánh dứa chua chua lạ miệng", slug: "banh-dua-chua-chua-la-mieng" },
  { videoId: "mxco_hfjVig", title: "Gì chứ bún cá là nghề của mình rồi. Nay mình chuyển sang cá thu nhaaaa.", slug: "gi-chu-bun-ca-la-nghe-cua-minh-roi-nay-minh-chuyen-sang-ca-thu-nhaaaa" },
  { videoId: "G3xz2DApaKM", title: "Shock vì món gà hấp nấm cực ngon", slug: "shock-vi-mon-ga-hap-nam-cuc-ngon" },
  { videoId: "i4m7X6VfCrQ", title: "Cá bục rim mắm, chiến thần tiêu diệt nồi cơm nhà bạn", slug: "ca-buc-rim-mam-chien-than-tieu-diet-noi-com-nha-ban" },
  { videoId: "A2oi2ys5bLA", title: "Canh cà bung, món cực hợp cho ngày mưa", slug: "canh-ca-bung-mon-cuc-hop-cho-ngay-mua" },
  { videoId: "Osvttbwzyw8", title: "osvttbwzyw8", slug: "osvttbwzyw8" },
  { videoId: "WqLlvoc1KQQ", title: "Cá kho dưa, ngon như Làng Vũ Đại", slug: "ca-kho-dua-ngon-nhu-lang-vu-dai" },
  { videoId: "VIeyASfstSc", title: "Ức vịt nướng nồi chiên không dầu ngon như nhà hàng 5 sao", slug: "uc-vit-nuong-noi-chien-khong-dau-ngon-nhu-nha-hang-5-sao" },
  { videoId: "FyFhZoh9PZM", title: "Đừng râu tôm nấu với ruột bầu nữa, nấu món này chồng mấy bà mới khen", slug: "dung-rau-tom-nau-voi-ruot-bau-nua-nau-mon-nay-chong-may-ba-moi-khen" },
  { videoId: "bVA-OuMikZM", title: "Mì tôm muối ớt mực giã tay, món cứu đói chờ lương", slug: "mi-tom-muoi-ot-muc-gia-tay-mon-cuu-doi-cho-luong" },
  { videoId: "-m3XW7O7KzY", title: "Canh bắp cải túi tiền tên thì lạ nhưng lại toàn nguyên liệu quen", slug: "canh-bap-cai-tui-tien-ten-thi-la-nhung-lai-toan-nguyen-lieu-quen" },
  { videoId: "5A2QAZBHFfI", title: "Bánh xèo tự làm cực dễ, topping ngập tràn, ăn siu đã", slug: "banh-xeo-tu-lam-cuc-de-topping-ngap-tran-an-siu-da" },
  { videoId: "shF1h8Osw5M", title: "Ba chỉ xào cá pháo, nghe rất lạ nhưng ăn lại cực ngon", slug: "ba-chi-xao-ca-phao-nghe-rat-la-nhung-an-lai-cuc-ngon" },
  { videoId: "5QXBsOXeuvQ", title: "5qxbsoxeuvq", slug: "5qxbsoxeuvq" },
  { videoId: "QDhj_mwRljQ", title: "Bò hấp cách thủy, giữa trọn vị ngọt của thịt", slug: "bo-hap-cach-thuy-giua-tron-vi-ngot-cua-thit" },
  { videoId: "mTZ8S_rjrO4", title: "Cơm chay 15 phút, thanh tịnh ngày rằm", slug: "com-chay-15-phut-thanh-tinh-ngay-ram" },
  { videoId: "J9ZEl01pjJw", title: "Làm cơm cháy chà bông bằng cháo gói, nghe lạ nhưng lại cực kỳ ngon", slug: "lam-com-chay-cha-bong-bang-chao-goi-nghe-la-nhung-lai-cuc-ky-ngon" },
  { videoId: "rm-7csR2DFI", title: "Bạn đã biết nấu bún riêu chay ngon đậm vị", slug: "ban-da-biet-nau-bun-rieu-chay-ngon-dam-vi" },
  { videoId: "VLtd0W2Nlho", title: "Sườn bò trái cây bí quyết ngon nhờ thành phần lạ mà quen", slug: "suon-bo-trai-cay-bi-quyet-ngon-nho-thanh-phan-la-ma-quen" },
  { videoId: "Ha85kSgt4Ik", title: "Món bún gì mà bay mùi 3 khu phố?", slug: "mon-bun-gi-ma-bay-mui-3-khu-pho" },
  { videoId: "o9SNRJzJv-c", title: "Bí quyết làm nem rán tôm khoai tây, xem ngay để không thất bại như thôi", slug: "bi-quyet-lam-nem-ran-tom-khoai-tay-xem-ngay-de-khong-that-bai-nhu-thoi" },
  { videoId: "QN4BOiTMcHU", title: "Lần đầu thử nấu canh bò sườn", slug: "lan-dau-thu-nau-canh-bo-suon" },
  { videoId: "iYIxGM_tUFQ", title: "Gỏi thịt bò rau má ngon lạ", slug: "goi-thit-bo-rau-ma-ngon-la" },
  { videoId: "6sRClWWR5j4", title: "Cơm quê rau luộc, khô chiên, vậy mà thèm mãi", slug: "com-que-rau-luoc-kho-chien-vay-ma-them-mai" },
  { videoId: "-LvNScC5NYw", title: "Tự làm Rau củ nướng giấy bạc nhu nhà hàng 5sao", slug: "tu-lam-rau-cu-nuong-giay-bac-nhu-nha-hang-5sao" },
  { videoId: "c36Bark3pCo", title: "Lâu lâu nhờ Bánh Tôm Hồ Tây thì lại tự làm món này", slug: "lau-lau-nho-banh-tom-ho-tay-thi-lai-tu-lam-mon-nay" },
  { videoId: "yN3av_tVTcc", title: "Tự làm cơm tấm sườn nướng mật ong bằng nồi chiên không dầu", slug: "tu-lam-com-tam-suon-nuong-mat-ong-bang-noi-chien-khong-dau" },
  { videoId: "MLP4VCam5NQ", title: "Tôm càng kho tàu ăn với dưa hấu đậm chất người Miền Tây", slug: "tom-cang-kho-tau-an-voi-dua-hau-dam-chat-nguoi-mien-tay" },
  { videoId: "cushnmasHB4", title: "Bún Bò Nam Bộ khác gì Bún Bò Huế?", slug: "bun-bo-nam-bo-khac-gi-bun-bo-hue" },
  { videoId: "jK6nYM3RMFE", title: "Tự nấu bánh canh cua cho cả nhà", slug: "tu-nau-banh-canh-cua-cho-ca-nha" },
  { videoId: "fttwS0-rhjU", title: "Cháo cá chép, dễ ăn lại cực kỳ bổ", slug: "chao-ca-chep-de-an-lai-cuc-ky-bo" },
  { videoId: "kdm8mQ9rWbs", title: "Lưỡi heo cháy tỏi, cho ngày mệt mỏi", slug: "luoi-heo-chay-toi-cho-ngay-met-moi" },
  { videoId: "ni5wPXk9v8o", title: "Đừng mua xá xíu ngoài tiệm nữa, tự làm tại nhà ngon và an toàn hơn!", slug: "dung-mua-xa-xiu-ngoai-tiem-nua-tu-lam-tai-nha-ngon-va-an-toan-hon" },
  { videoId: "J8J_nisCH5M", title: "Mắm cá kho, món ngon, nhưng nặng mùi, dễ gây mất đoàn kết 🤣🤣", slug: "mam-ca-kho-mon-ngon-nhung-nang-mui-de-gay-mat-doan-ket" },
  { videoId: "QeBOaJHIVtk", title: "Bánh Đa Cua Hải Phòng, nấu trong 5 phút", slug: "banh-da-cua-hai-phong-nau-trong-5-phut" },
  { videoId: "p0TlJxD_lWU", title: "Thịt kho trứng cút vẫn là món ruột của mình", slug: "thit-kho-trung-cut-van-la-mon-ruot-cua-minh" },
  { videoId: "_x8c9-IgJIY", title: "Làm hộp pate gan để dành ăn sáng bánh mì hay xôi đều ngon", slug: "lam-hop-pate-gan-de-danh-an-sang-banh-mi-hay-xoi-deu-ngon" },
  { videoId: "Hou6G_KUQwI", title: "Bún Mọc Ốc – Ngon Bất Ngờ Mà Làm Rất Dễ", slug: "bun-moc-oc-ngon-bat-ngo-ma-lam-rat-de" },
  { videoId: "hOiPqEYYG5Q", title: "Món cháo chồng ăn mà vợ cười tủm tỉm 😂😂", slug: "mon-chao-chong-an-ma-vo-cuoi-tum-tim" },
  { videoId: "zmQDsOa4Tdg", title: "Ai nghĩ Trứng Chiên là dễ thì xem hết video này đi", slug: "ai-nghi-trung-chien-la-de-thi-xem-het-video-nay-di" },
  { videoId: "OLRAN-EWMRY", title: "Bạn thích xôi mặn Miền Tây hay xôi khúc Hà Nội?", slug: "ban-thich-xoi-man-mien-tay-hay-xoi-khuc-ha-noi" },
  { videoId: "kkKT_bhCM6E", title: "Bánh tart phomai ăn sáng, làm cực nhanh, dinh dưỡng, cả nhà đều mê", slug: "banh-tart-phomai-an-sang-lam-cuc-nhanh-dinh-duong-ca-nha-deu-me" },
  { videoId: "JAL9vcwmYFU", title: "Cùng thẩm định Quốc Tịch qua bát Bún Bò Huế tự nấu!", slug: "cung-tham-dinh-quoc-tich-qua-bat-bun-bo-hue-tu-nau" },
  { videoId: "rX5C4JLyff4", title: "BÚN CÁ DIÊU HỒNG CHIÊN đổi vị", slug: "bun-ca-dieu-hong-chien-doi-vi" },
  { videoId: "cXMh5bDFm3A", title: "Bún ốc không cần hầm xương, vẫn ngọt thanh, bí quyết ở đây.", slug: "bun-oc-khong-can-ham-xuong-van-ngot-thanh-bi-quyet-o-day" },
  { videoId: "O6BcH1SeLP8", title: "Cuối tuần đổi vị với món Há cảo tôm thịt kiểu Nhật 🥢", slug: "cuoi-tuan-doi-vi-voi-mon-ha-cao-tom-thit-kieu-nhat" },
  { videoId: "_h2JmCEITgw", title: "Bí quyết vịt nấu chao không bị tanh", slug: "bi-quyet-vit-nau-chao-khong-bi-tanh" },
  { videoId: "d8Co3y1iLpM", title: "d8co3y1ilpm", slug: "d8co3y1ilpm" },
  { videoId: "u2OqNG5e4wA", title: "Tự làm nồi thịt kho để ăn xôi", slug: "tu-lam-noi-thit-kho-de-an-xoi" },
  { videoId: "3yLsuTJQO2E", title: "Tôm bỏ lò phomai đổi món cho cả nhà ngày lễ", slug: "tom-bo-lo-phomai-doi-mon-cho-ca-nha-ngay-le" },
  { videoId: "9N9-kAESLOk", title: "Ai cũng có thể tự làm bánh bao cực ngon tại nhà | bí mật cách làm ở video này", slug: "ai-cung-co-the-tu-lam-banh-bao-cuc-ngon-tai-nha-bi-mat-cach-lam-o-vide" },
  { videoId: "nRMTkREvAFQ", title: "Đừng ra hàng nữa, tự làm Cơm gà mắm tỏi ngon hơn tiệm", slug: "dung-ra-hang-nua-tu-lam-com-ga-mam-toi-ngon-hon-tiem" },
  { videoId: "k_i9dEP2V1A", title: "xôi chim câu đổi món", slug: "xoi-chim-cau-doi-mon" },
  { videoId: "WYJOUAVFmU8", title: "Trời nóng ăn gì? Thử ngay Vịt Nấu Khóm giải nhiệt, đưa cơm cực kỳ", slug: "troi-nong-an-gi-thu-ngay-vit-nau-khom-giai-nhiet-dua-com-cuc-ky" },
  { videoId: "nCol6-txSc0", title: "Mẹo kho Vịt với gừng già: Màu cánh gián đẹp tự nhiên, thơm nức mũi", slug: "meo-kho-vit-voi-gung-gia-mau-canh-gian-dep-tu-nhien-thom-nuc-mui" },
  { videoId: "zDir7VKvOZg", title: "Bật Mí Bí Mật Nước Lèo Hủ Tiếu Mực Vũng Tàu, thay thành Bún vẫn ngon nhức nách", slug: "bat-mi-bi-mat-nuoc-leo-hu-tieu-muc-vung-tau-thay-thanh-bun-van-ngon-nh" },
  { videoId: "EnjO3MZC6Pw", title: "Đố bạn Mắm Chưng khác gì Chả Trứng?", slug: "do-ban-mam-chung-khac-gi-cha-trung" },
  { videoId: "dcFuUmm2s08", title: "Bún Bò Cải Chua, bữa ăn trong 5 phút", slug: "bun-bo-cai-chua-bua-an-trong-5-phut" },
  { videoId: "sQtQiKTff78", title: "Gà bóp gỏi, làm sao cho ngọt?", slug: "ga-bop-goi-lam-sao-cho-ngot" },
  { videoId: "WY0B4i67jlY", title: "Món gì vừa ngon, vừa giảm cân. Đấy, miến gà 15 phút, ngon, bổ, khỏe", slug: "mon-gi-vua-ngon-vua-giam-can-day-mien-ga-15-phut-ngon-bo-khoe" },
  { videoId: "uDEsVoO4NUs", title: "Đừng rã đông bằng nước lạnh nữa, hãy thử ngay cách này", slug: "dung-ra-dong-bang-nuoc-lanh-nua-hay-thu-ngay-cach-nay" },
  { videoId: "0QuGk_Co0no", title: "Cải chua Việt Nam chắc chắn đa di năng hơn Kim Chi Hàn Quốc", slug: "cai-chua-viet-nam-chac-chan-da-di-nang-hon-kim-chi-han-quoc" },
  { videoId: "AQc01TJQsCU", title: "Ăn chay đụng, đơn giản vì quá ngon với món súp chay này", slug: "an-chay-dung-don-gian-vi-qua-ngon-voi-mon-sup-chay-nay" },
  { videoId: "Xf593ZkhzkI", title: "Lười quá thì cứ cho hết mọi thứ vào nấu chung như các pháp sư Trung Hoa, nhưng ngon vô địch", slug: "luoi-qua-thi-cu-cho-het-moi-thu-vao-nau-chung-nhu-cac-phap-su-trung-ho" },
  { videoId: "jbN654oS_SY", title: "Ai nói canh cá tanh thì xem hết", slug: "ai-noi-canh-ca-tanh-thi-xem-het" },
  { videoId: "cExjVfl7qfA", title: "Đố bạn Bún Bò Đà Nẵng khác gì Bún Bò Huế?", slug: "do-ban-bun-bo-da-nang-khac-gi-bun-bo-hue" },
  { videoId: "JnzTpCQa92A", title: "Bún Cá Kim Chi, sự kết hợp của Oppa và Dân Ca Quan Họ", slug: "bun-ca-kim-chi-su-ket-hop-cua-oppa-va-dan-ca-quan-ho" },
  { videoId: "EkvSF0fqgSc", title: "Bánh canh giò heo, dễ nấu, dễ ăn", slug: "banh-canh-gio-heo-de-nau-de-an" },
  { videoId: "uzZxYxybqf0", title: "Bao tử trộn gỏi, giòn sần sật, chua chua", slug: "bao-tu-tron-goi-gion-san-sat-chua-chua" },
  { videoId: "rW6Uht5x7Rw", title: "Hôm nay ăn chay, giảm nghiệp với món canh bún nha.", slug: "hom-nay-an-chay-giam-nghiep-voi-mon-canh-bun-nha" },
  { videoId: "4EUqZXkqZRw", title: "Cá Chiên Giòn Lá Lốt | Món Ngon Dễ Làm, Vị Quê Nhà", slug: "ca-chien-gion-la-lot-mon-ngon-de-lam-vi-que-nha" },
  { videoId: "g5I59gN5ZpQ", title: "Bún Gà nấu lá giang, chua chua, có thể ăn như lẩu", slug: "bun-ga-nau-la-giang-chua-chua-co-the-an-nhu-lau" },
  { videoId: "AaVVA1yembA", title: "Súp(canh) tôm măng tươi, tưởng không ngon mà ngon không tưởng", slug: "supcanh-tom-mang-tuoi-tuong-khong-ngon-ma-ngon-khong-tuong" },
  { videoId: "eAqkKoVO6KM", title: "Gỏi bò với cà pháo ngon hơn tất thảy sơn hào hải vị", slug: "goi-bo-voi-ca-phao-ngon-hon-tat-thay-son-hao-hai-vi" },
  { videoId: "7DdkY6J5_Yw", title: "Bí quyết miến xào không bị vón cục", slug: "bi-quyet-mien-xao-khong-bi-von-cuc" },
  { videoId: "GSQzMHxxsq0", title: "Bánh Xèo Tôm Nhảy | Hương Vị Miền Tây Gọi Mùa Nắng Về", slug: "banh-xeo-tom-nhay-huong-vi-mien-tay-goi-mua-nang-ve" },
  { videoId: "y3ui4u5MQyw", title: "Món canh \"vàng\" cho sức khỏe: Đủ chất, nhẹ bụng, chuẩn vị cơm nhà", slug: "mon-canh-vang-cho-suc-khoe-du-chat-nhe-bung-chuan-vi-com-nha" },
  { videoId: "g-C48akpMeE", title: "Khô tiêu, món chay cực kỳ đưa cơm", slug: "kho-tieu-mon-chay-cuc-ky-dua-com" },
  { videoId: "k5WO7w1XEj4", title: "Cá nục kho với nước mía, kho lâu cho rục sươn luôn thì hao cơm phải biết", slug: "ca-nuc-kho-voi-nuoc-mia-kho-lau-cho-ruc-suon-luon-thi-hao-com-phai-bie" },
  { videoId: "ya4aQX-iotI", title: "Làm cơm trứng", slug: "lam-com-trung" },
  { videoId: "a9PwmnvgfGA", title: "Bạn đã biết cách muối cà pháo chưa?", slug: "ban-da-biet-cach-muoi-ca-phao-chua" },
  { videoId: "jxdIINXQ-cs", title: "Trời nóng nóng là lại thèm vịt om sấu chua chua giải nhiệt", slug: "troi-nong-nong-la-lai-them-vit-om-sau-chua-chua-giai-nhiet" },
  { videoId: "-fJEF8JXLes", title: "Món nào được xem là Quốc Thực?", slug: "mon-nao-duoc-xem-la-quoc-thuc" },
  { videoId: "N-Vp0T6saTs", title: "Miến gà, miến vịt quen quá, nay mình nấu miến sụn húng(2)", slug: "mien-ga-mien-vit-quen-qua-nay-minh-nau-mien-sun-hung2" },
  { videoId: "JeD4I_6drzo", title: "Hột Vịt Lộn Um Bầu | Vị Quê Nhà Ấm Lòng", slug: "hot-vit-lon-um-bau-vi-que-nha-am-long" },
  { videoId: "b0pX-qHazZQ", title: "Món này cực kỳ hợp với buổi sáng chill chill", slug: "mon-nay-cuc-ky-hop-voi-buoi-sang-chill-chill" },
  { videoId: "04JLufkiAWQ", title: "Ngán gà luộc thì chuyển qua làm gà nướng mắm nhĩ nè", slug: "ngan-ga-luoc-thi-chuyen-qua-lam-ga-nuong-mam-nhi-ne" },
  { videoId: "t9GTGD4D3HE", title: "Bún Quậy Phú Quốc lại có nguồn gốc từ Gia Lai?", slug: "bun-quay-phu-quoc-lai-co-nguon-goc-tu-gia-lai" },
  { videoId: "i07nW9RO4j4", title: "Vịt quay Bắc Kinh bằng nồi chiên không dầu và nước sốt bí truyền", slug: "vit-quay-bac-kinh-bang-noi-chien-khong-dau-va-nuoc-sot-bi-truyen" },
  { videoId: "Ue_SUIJh4WA", title: "Tuyệt chiêu gà chiên bơ tỏi già trẻ trong nhà ai cũng mê", slug: "tuyet-chieu-ga-chien-bo-toi-gia-tre-trong-nha-ai-cung-me" },
  { videoId: "ZKATI2sToJ4", title: "Bánh Đúc Thịt | Hương Vị Thân Quen Từ Món Ăn Tuổi Thơ", slug: "banh-duc-thit-huong-vi-than-quen-tu-mon-an-tuoi-tho" },
  { videoId: "tRNPiqtLGK8", title: "Lẩu cá Thác Lác mix Trứng vịt lộn, nghe đau bụng nhưng ăn căng bụng", slug: "lau-ca-thac-lac-mix-trung-vit-lon-nghe-dau-bung-nhung-an-cang-bung" },
  { videoId: "E3zWJu0GjOc", title: "Cà pháo xào ba chỉ lá lốt, sự kết hợp không thể hợp hơn", slug: "ca-phao-xao-ba-chi-la-lot-su-ket-hop-khong-the-hop-hon" },
  { videoId: "kQlyhfJSGxg", title: "Đừng luộc gà nữa, đổi sang món gà hấm nấp đi, đảm bảo ngon lành hơn", slug: "dung-luoc-ga-nua-doi-sang-mon-ga-ham-nap-di-dam-bao-ngon-lanh-hon" },
  { videoId: "n2NOEvyp-JA", title: "Cá Rang Muối | Giòn Rụm Ấm Áp Hương Vị Gia Đình", slug: "ca-rang-muoi-gion-rum-am-ap-huong-vi-gia-dinh" },
  { videoId: "4XJxSLHxxZ8", title: "Nem Cua Bể | Hương Vị Hải Phòng Thơm Lừng Mùa Hè", slug: "nem-cua-be-huong-vi-hai-phong-thom-lung-mua-he" },
  { videoId: "jshi7XqOQ4I", title: "Bò Hấp Bia | Mùi Thơm Kéo Cả Nhà Về Mâm Cơm", slug: "bo-hap-bia-mui-thom-keo-ca-nha-ve-mam-com" },
  { videoId: "ZEL6E35BQSI", title: "Tại sao Kim Chi là Quốc Thực của Hàn Quốc còn Dưa Chua của Việt Nam thì không", slug: "tai-sao-kim-chi-la-quoc-thuc-cua-han-quoc-con-dua-chua-cua-viet-nam-th" },
  { videoId: "I_raQ8QPYP8", title: "Canh Mồng Tơi | Vị Thanh Mát Của Mùa Hè", slug: "canh-mong-toi-vi-thanh-mat-cua-mua-he" },
  { videoId: "S9SYc33ppx8", title: "Nem Lụi Bọc Sả Nướng | Hương Vị Quê Nhà Ấm Áp Ngày Cuối Tuần", slug: "nem-lui-boc-sa-nuong-huong-vi-que-nha-am-ap-ngay-cuoi-tuan" },
  { videoId: "LkmX_OeDu88", title: "Bò Nhúng Dấm | Vị Chua Ngọt Cứ Mãi Về Trong Tim", slug: "bo-nhung-dam-vi-chua-ngot-cu-mai-ve-trong-tim" },
  { videoId: "AFGn-kRvspQ", title: "Bánh canh cá lóc", slug: "banh-canh-ca-loc" },
  { videoId: "GSVgL0LFIU4", title: "Cách làm bánh bao nhân thịt thơm ngon tại nhà siêu dễ", slug: "cach-lam-banh-bao-nhan-thit-thom-ngon-tai-nha-sieu-de" },
  { videoId: "Y-sAcgwA4wY", title: "Chả Giò Cá | Từng Cuốn Vàng Giòn Gợi Nhớ Vị Quê Nhà", slug: "cha-gio-ca-tung-cuon-vang-gion-goi-nho-vi-que-nha" },
  { videoId: "LVUUPuvesTg", title: "Bánh Đúc Lạc | Vị Ngọt Thanh Của Tuổi Thơ Ổn Ào", slug: "banh-duc-lac-vi-ngot-thanh-cua-tuoi-tho-on-ao" },
  { videoId: "cMA0ACXnTi8", title: "cma0acxnti8", slug: "cma0acxnti8" },
  { videoId: "qITHhaIDEfY", title: "Muốn giảm cân nhưng vẫn cần ăn ngon", slug: "muon-giam-can-nhung-van-can-an-ngon" },
  { videoId: "mhET3LLG6ZI", title: "Nem Chay Ram Rí | Vị Giòn Tan Của Món Ăn Tuổi Thơ", slug: "nem-chay-ram-ri-vi-gion-tan-cua-mon-an-tuoi-tho" },
  { videoId: "K1ne_88KBFQ", title: "Cháo Hạt Kê Bí Đỏ | Món Ngọt Ấm Lòng Cho Ngày Se Lạnh", slug: "chao-hat-ke-bi-do-mon-ngot-am-long-cho-ngay-se-lanh" },
  { videoId: "RfmYDZCdi-Y", title: "Bí quyết làm bò nhúng dấm với nước dùng ngọt thanh", slug: "bi-quyet-lam-bo-nhung-dam-voi-nuoc-dung-ngot-thanh" },
  { videoId: "oC_eh-3-Frw", title: "Hôm nay mọi người nghỉ lễ hết, thôi thì mình đăng video mang cơm đi làm cho đỡ bùn", slug: "hom-nay-moi-nguoi-nghi-le-het-thoi-thi-minh-dang-video-mang-com-di-lam" },
  { videoId: "eCKz5HNZgOw", title: "Cá Hồi áp chảo ngâm tương, cay cay, chua chua, ngon là lạ", slug: "ca-hoi-ap-chao-ngam-tuong-cay-cay-chua-chua-ngon-la-la" },
  { videoId: "bz9TxS2z090", title: "Bún Thái Chay Thanh Đạm | Thai Veg Noodle Soup", slug: "bun-thai-chay-thanh-dam-thai-veg-noodle-soup" },
  { videoId: "hBrR3FOCjJM", title: "Cơm nhà 3 món, nấu 20 phút là xong", slug: "com-nha-3-mon-nau-20-phut-la-xong" },
  { videoId: "jYnMLPXEjDE", title: "Món lười nhưng đủ dưỡng chất", slug: "mon-luoi-nhung-du-duong-chat" },
  { videoId: "rSLmOkDUqwc", title: "Cơm gà theo kiểu Hàn Quốc", slug: "com-ga-theo-kieu-han-quoc" },
  { videoId: "PX_s6zSgiz8", title: "Khoai lang nướng phô mai | Món ăn vặt 'bao dính' cho ngày se lạnh", slug: "khoai-lang-nuong-pho-mai-mon-an-vat-bao-dinh-cho-ngay-se-lanh" },
  { videoId: "BEASGBlsxqc", title: "Nấu nhanh tô bún sườn cà chua cho cả nhà ăn sáng cuối tuần", slug: "nau-nhanh-to-bun-suon-ca-chua-cho-ca-nha-an-sang-cuoi-tuan" },
  { videoId: "bkkFpMO9y54", title: "Sốt Cà Chua Tươi Ngon | Tự Làm Chuẩn Vị Tại Nhà", slug: "sot-ca-chua-tuoi-ngon-tu-lam-chuan-vi-tai-nha" },
  { videoId: "VwTiLOQMUDc", title: "Honey sesame chicken thigh | Đùi gà sốt mật ong", slug: "honey-sesame-chicken-thigh-dui-ga-sot-mat-ong" },
  { videoId: "WPUZwDeaLZs", title: "Nghêu hấp thái siu nhanh với gói gia vị sẵn", slug: "ngheu-hap-thai-siu-nhanh-voi-goi-gia-vi-san" },
  { videoId: "W566mQIK6VY", title: "Phồng tôm mà đem nấu bánh canh thì sẽ như thế nào?", slug: "phong-tom-ma-dem-nau-banh-canh-thi-se-nhu-the-nao" },
  { videoId: "QCdfmL5dqu4", title: "Vịt nấu khoai, có thêm sấu, khoai, cốt dừa", slug: "vit-nau-khoai-co-them-sau-khoai-cot-dua" },
  { videoId: "BOaGpFIuX7g", title: "Bún mắm chay full topping như mặn", slug: "bun-mam-chay-full-topping-nhu-man" },
  { videoId: "QWg6YAtpPXk", title: "Bí mật chế biến cá hồi sốt cam cực ngon, không hề tanh", slug: "bi-mat-che-bien-ca-hoi-sot-cam-cuc-ngon-khong-he-tanh" },
  { videoId: "1mNvNivDZ94", title: "Tự nấu bún bò từ a-z, hơi kỳ công, nhưng thành quả là xứng đáng", slug: "tu-nau-bun-bo-tu-a-z-hoi-ky-cong-nhung-thanh-qua-la-xung-dang" },
  { videoId: "b7eaIX2pPsI", title: "Món mà đi đâu tôi cũng nhớ", slug: "mon-ma-di-dau-toi-cung-nho" },
  { videoId: "vuks31dmcag", title: "Cách Làm Bánh Cuốn Dẻo Mềm Tại Nhà Đơn Giản Nhất", slug: "cach-lam-banh-cuon-deo-mem-tai-nha-don-gian-nhat" },
  { videoId: "410D-BJh8O4", title: "Bí Ý Tưởng? Nấu Ngay Canh Ngũ Sắc Siêu Dễ!", slug: "bi-y-tuong-nau-ngay-canh-ngu-sac-sieu-de" },
  { videoId: "fP86vZaoahI", title: "[Góc chi tiết] Cách Làm Cá Diêu Hồng Nướng Giấy Bạc Bằng Nồi Chiên Không Dầu Siêu Ngọt Thịt", slug: "goc-chi-tiet-cach-lam-ca-dieu-hong-nuong-giay-bac-bang-noi-chien-khong" },
  { videoId: "MpwWs794qrA", title: "Bí quyết kho cá ngừ thấm ngon, đậm đà", slug: "bi-quyet-kho-ca-ngu-tham-ngon-dam-da" },
  { videoId: "4WELrrWNCTk", title: "Ba chỉ rim dứa, cực kỳ đưa cơm", slug: "ba-chi-rim-dua-cuc-ky-dua-com" },
  { videoId: "9Qu3az_rUcY", title: "Canh hến cà chua, món canh giải nhiệt ngày nóng", slug: "canh-hen-ca-chua-mon-canh-giai-nhiet-ngay-nong" },
  { videoId: "0MQWz9P60cc", title: "Gà Sốt Cay | Vị Ngọt Thơm Quyện Cùng Thời Gian", slug: "ga-sot-cay-vi-ngot-thom-quyen-cung-thoi-gian" },
  { videoId: "HzhxrJPxsGQ", title: "[Góc chi tiết] Cách làm chả mỡ giòn sần sật cực kỳ đơn giản mà ai cũng làm được", slug: "goc-chi-tiet-cach-lam-cha-mo-gion-san-sat-cuc-ky-don-gian-ma-ai-cung-l" },
  { videoId: "9thlvKEHqzU", title: "[Góc chi tiết] Cơm tầm Sườn Bì Chả chuẩn vị Sài Gòn", slug: "goc-chi-tiet-com-tam-suon-bi-cha-chuan-vi-sai-gon" },
  { videoId: "xm_svMAlPHM", title: "Chân Gà Sả Tắc | Chua Cay Thơm Lừng Kích Thích Vị Giác", slug: "chan-ga-sa-tac-chua-cay-thom-lung-kich-thich-vi-giac" },
  { videoId: "Jh3hoFdD410", title: "Gỏi Cuốn Tôm Thịt | Vị Quê Nhà Mát Lạnh Giữa Ngày Hè", slug: "goi-cuon-tom-thit-vi-que-nha-mat-lanh-giua-ngay-he" },
  { videoId: "2tobavKCpE4", title: "Bánh Hẹ Chiên Giòn Rụm | Cắn Một Miếng Là Ghiền 🤤", slug: "banh-he-chien-gion-rum-can-mot-mieng-la-ghien" },
  { videoId: "7upif5hLrc8", title: "Cách làm Gỏi Bò Sốt Thái Chua Cay Đậm Đà Đơn Giản Tại Nhà", slug: "cach-lam-goi-bo-sot-thai-chua-cay-dam-da-don-gian-tai-nha" },
  { videoId: "NWT6wluS8bk", title: "[Góc chi tiết] Gợi ý 3 Món Chay Thanh Đạm, Dễ Làm Cho Rằm & Mùng 1 | Góc Bếp", slug: "goc-chi-tiet-goi-y-3-mon-chay-thanh-dam-de-lam-cho-ram-mung-1-goc-bep" },
  { videoId: "1e0uKQ83-U0", title: "Bún Bò Lười: Nhanh Gọn, Ngon Miệng Mà Không Cần Nêm Nếm Nhiều", slug: "bun-bo-luoi-nhanh-gon-ngon-mieng-ma-khong-can-nem-nem-nhieu" },
  { videoId: "TOs81Tw7Yvk", title: "Bí Quyết Làm Nước Lẩu Chua Cay Siêu Ngon, Món Này Ăn Với Bún là cực kỳ hợp", slug: "bi-quyet-lam-nuoc-lau-chua-cay-sieu-ngon-mon-nay-an-voi-bun-la-cuc-ky" },
  { videoId: "8m5yi6VIN4A", title: "Miến Hấp Tôm Mực Ngon Tuyệt Hảo - Công Thức Đơn Giản Tại Nhà", slug: "mien-hap-tom-muc-ngon-tuyet-hao-cong-thuc-don-gian-tai-nha" },
  { videoId: "nopitYdwUQw", title: "Bí quyết ngủ ngon mỗi ngày với món hạt sen hầm kỉ tử", slug: "bi-quyet-ngu-ngon-moi-ngay-voi-mon-hat-sen-ham-ki-tu" },
  { videoId: "g5ZD383RRDk", title: "Thính Tai Heo Cuốn Bánh Tráng | Giòn Sần Sật Cực Cuốn 🤤", slug: "thinh-tai-heo-cuon-banh-trang-gion-san-sat-cuc-cuon" },
  { videoId: "LsfUeBa-jW4", title: "Mướp Đắng Nhồi Thịt - Vị Đắng Thanh Cùng Cơm Nhà", slug: "muop-dang-nhoi-thit-vi-dang-thanh-cung-com-nha" },
  { videoId: "f04lQ0emIpM", title: "Bánh Cuốn Nhân Thịt | Hương Vị Quê Nhà Ấm Áp Ngày Đông", slug: "banh-cuon-nhan-thit-huong-vi-que-nha-am-ap-ngay-dong" },
  { videoId: "ma5Lt86yv58", title: "Mực ngào, món ăn được vạn người mê", slug: "muc-ngao-mon-an-duoc-van-nguoi-me" },
  { videoId: "5fg-g_9gKn8", title: "Gỏi Tai Heo Tôm | Giòn Giòn Sần Sật Nhớ Về Khói Bếp Xưa", slug: "goi-tai-heo-tom-gion-gion-san-sat-nho-ve-khoi-bep-xua" },
  { videoId: "38S-j4f6YxQ", title: "Bánh Khoai Mỡ Phô Mai Kéo Sợi | Cắn Một Miếng Là Mê 🤤", slug: "banh-khoai-mo-pho-mai-keo-soi-can-mot-mieng-la-me" },
  { videoId: "Eu0RzQLmjzw", title: "Bí quyết nấu Phở Gà nước trong, thơm nức, chuẩn vị truyền thống", slug: "bi-quyet-nau-pho-ga-nuoc-trong-thom-nuc-chuan-vi-truyen-thong" },
  { videoId: "iqtlPOd2eZw", title: "Cánh Gà Rang Muối | Giòn Rụm Vị Quê Nhà Trên Mâm Cơm", slug: "canh-ga-rang-muoi-gion-rum-vi-que-nha-tren-mam-com" },
  { videoId: "wRwS1iSO61o", title: "Kết hợp Khoai lang - Xoài - Phomai lại ra 1 món ăn xuất sắc", slug: "ket-hop-khoai-lang-xoai-phomai-lai-ra-1-mon-an-xuat-sac" },
  { videoId: "RnuJPo4H0JU", title: "Canh bầu nấu mọc tôm | Từng sợi bầu mướt mát gọi mùa hè", slug: "canh-bau-nau-moc-tom-tung-soi-bau-muot-mat-goi-mua-he" },
  { videoId: "OTLOfjKrpaw", title: "Bánh Chuối Bột Nếp Trong Dẻo Ngoài Giòn | Ăn Một Miếng Là Mê", slug: "banh-chuoi-bot-nep-trong-deo-ngoai-gion-an-mot-mieng-la-me" },
  { videoId: "743y7PhDtPA", title: "​Bí Quyết Nấu Miến Gà Nước Trong Veo, Sợi Dai Không Bị Nát 🍜", slug: "bi-quyet-nau-mien-ga-nuoc-trong-veo-soi-dai-khong-bi-nat" },
  { videoId: "03IqlmDKU8Q", title: "Tôm Rang Thịt Ba Chỉ | Hương Vị Quê Nhà Gọi Bữa Cơm Chiều", slug: "tom-rang-thit-ba-chi-huong-vi-que-nha-goi-bua-com-chieu" },
  { videoId: "3bldw80QPlA", title: "Bò Cuốn Cải Xanh | Hương Vị Quê Nhà Trong Món Ăn Hiện Đại", slug: "bo-cuon-cai-xanh-huong-vi-que-nha-trong-mon-an-hien-dai" },
  { videoId: "ULtujinEOvg", title: "[Góc chi tiết] Đừng bỏ qua bí quyết làm thịt xiên nướng | ăn chơi, bún thịt nướng, bánh mì đều ngon", slug: "goc-chi-tiet-dung-bo-qua-bi-quyet-lam-thit-xien-nuong-an-choi-bun-thit" },
  { videoId: "nTupIglgUWE", title: "Gỏi Bưởi Tôm Thịt - Giòn Thanh, Ngọt Tự Nhiên Cho Ngày Thèm", slug: "goi-buoi-tom-thit-gion-thanh-ngot-tu-nhien-cho-ngay-them" },
  { videoId: "hsWZs7QfSE8", title: "Bò xào khoai tây, lại thêm một món ngon cho mâm cơm", slug: "bo-xao-khoai-tay-lai-them-mot-mon-ngon-cho-mam-com" },
  { videoId: "EylH3U7lK6M", title: "Bò Xốp Mắm Nhĩ - Đậm Đà Vị Quê Nhà Trong Từng Sợi Thịt", slug: "bo-xop-mam-nhi-dam-da-vi-que-nha-trong-tung-soi-thit" },
  { videoId: "kufhDR_zITU", title: "Vịt Luộc Chấm Xì Dầu | Hương Vị Quê Nhà Trong Từng Miếng", slug: "vit-luoc-cham-xi-dau-huong-vi-que-nha-trong-tung-mieng" },
  { videoId: "0yFXu0BYFyY", title: "[Góc chi tiết] Cơm gà xối mỡ không khó đâu", slug: "goc-chi-tiet-com-ga-xoi-mo-khong-kho-dau" },
  { videoId: "w5lCxHIqkTk", title: "Ếch Xào Lá Lốt - Vị Cay Nồng Của Tuổi Thơ Ơi", slug: "ech-xao-la-lot-vi-cay-nong-cua-tuoi-tho-oi" },
  { videoId: "sqJzS8z-pfk", title: "Nộm Tai Heo Xoài | Giòn Sần Sật Thơm Lừng Khó Cưỡng", slug: "nom-tai-heo-xoai-gion-san-sat-thom-lung-kho-cuong" },
  { videoId: "mio_Kl_7OAo", title: "Bánh Đúc Cốt Dừa - Món Ăn Gắn  Liền Với Tuổi Thơ", slug: "banh-duc-cot-dua-mon-an-gan-lien-voi-tuoi-tho" },
  { videoId: "Uq4MyH-I0kw", title: "Thạch Đường Đen - \"Xả Vai\" Với Món Tráng Miệng Thanh Mát", slug: "thach-duong-den-xa-vai-voi-mon-trang-mieng-thanh-mat" },
  { videoId: "iRcDSg5NkEE", title: "Đậu Hũ Chiên Giòn Sốt Tứ Xuyên - Vị Cay Mặn Đậm Đà Khó Cưỡng", slug: "dau-hu-chien-gion-sot-tu-xuyen-vi-cay-man-dam-da-kho-cuong" },
  { videoId: "mDBPGYgY72k", title: "Trân Châu Nhân Ngô | Viên Ngọt Tan Như Tan Tầm Mưa Hạ", slug: "tran-chau-nhan-ngo-vien-ngot-tan-nhu-tan-tam-mua-ha" },
  { videoId: "Rp1LLJw65j4", title: "Tôm Rang Muối - Giòn Tan Nhanh Như Một Cái Chớp Mắt", slug: "tom-rang-muoi-gion-tan-nhanh-nhu-mot-cai-chop-mat" },
  { videoId: "hK-QbBpc78o", title: "Chả Ốc | Vị Quê Nhà Ngay Giữa Lòng Phố Thị", slug: "cha-oc-vi-que-nha-ngay-giua-long-pho-thi" },
  { videoId: "CD6-Z8OnRKU", title: "Bún Riêu Cua: Cách nấu đơn giản, chuẩn vị, đậm đà hương vị Việt", slug: "bun-rieu-cua-cach-nau-don-gian-chuan-vi-dam-da-huong-vi-viet" },
  { videoId: "73KL7J8d7SI", title: "Chân Gà Hấp Hành Gừng | Mùi Thơm Quyến Luyến Kéo Cả Nhà Về", slug: "chan-ga-hap-hanh-gung-mui-thom-quyen-luyen-keo-ca-nha-ve" },
  { videoId: "jwZ6ncYw45o", title: "Vịt Cuốn Bánh Tráng | Hương Vị Xưa Len Lỏi Trong Món Ăn Gia Đình", slug: "vit-cuon-banh-trang-huong-vi-xua-len-loi-trong-mon-an-gia-dinh" },
  { videoId: "qPLfNQwqZDA", title: "Bò Nhúng Dấm Nóng Hổi, Mềm Tan, Chấm Mắm Nêm Thơm Lừng", slug: "bo-nhung-dam-nong-hoi-mem-tan-cham-mam-nem-thom-lung" },
  { videoId: "WY8LqJsbbRw", title: "Cá Nục Kho Nước Mía - Vị Ngọt Thơm Ấm Áp Bữa Cơm Gia Đình", slug: "ca-nuc-kho-nuoc-mia-vi-ngot-thom-am-ap-bua-com-gia-dinh" },
  { videoId: "ahCgJSFDv7s", title: "Bánh Chuối Hấp - Ngọt Lành Hương Vị Tuổi Thơ", slug: "banh-chuoi-hap-ngot-lanh-huong-vi-tuoi-tho" },
  { videoId: "-jLY0OiO1_s", title: "Bánh Bông Lan | Tự Tay Làm Chiếc Bánh Mềm Xốp Như Mây", slug: "banh-bong-lan-tu-tay-lam-chiec-banh-mem-xop-nhu-may" },
  { videoId: "vIgS3ahfXOk", title: "Cách làm Cơm Chiên Hải Sản Thơm Ngon Chuẩn Vị Nhà Hàng", slug: "cach-lam-com-chien-hai-san-thom-ngon-chuan-vi-nha-hang" },
  { videoId: "2zXVKshd3MU", title: "Bún Trộn Mắm Nêm | Vị Quê Nhà Giữa Phố Thị Nhộn Nhịp", slug: "bun-tron-mam-nem-vi-que-nha-giua-pho-thi-nhon-nhip" },
  { videoId: "THxmBbUwDUk", title: "Miến Vịt Luộc Chấm Mắm Gừng: Món Ngon Đơn Giản Tại Nhà", slug: "mien-vit-luoc-cham-mam-gung-mon-ngon-don-gian-tai-nha" },
  { videoId: "VY-xAzsaVLk", title: "Cá Hấp Lá Chuối | Mùi Thơm Nhớ Mãi Vị Quê Nhà", slug: "ca-hap-la-chuoi-mui-thom-nho-mai-vi-que-nha" },
  { videoId: "m4P2Gc2UyF0", title: "Bánh Mì Nướng Bơ Tỏi Ngô Phô Mai - Mùi Thơm Tan Chảy Cuốn Hút", slug: "banh-mi-nuong-bo-toi-ngo-pho-mai-mui-thom-tan-chay-cuon-hut" },
  { videoId: "haX5_VKp_iM", title: "Bê Hấp Lá Lốt - Vị Ngon Mộc Mạc, Gọi Cả Nhà Về", slug: "be-hap-la-lot-vi-ngon-moc-mac-goi-ca-nha-ve" },
  { videoId: "PkQsWEopK2E", title: "Xôi Ngô Dừa - Hương Vị Tuổi Thơ Ngọt Ngào", slug: "xoi-ngo-dua-huong-vi-tuoi-tho-ngot-ngao" },
  { videoId: "O7i1svOpIFo", title: "Giò Nây Đặc Sản Thái Bình - Món Lạ Mà Quen", slug: "gio-nay-dac-san-thai-binh-mon-la-ma-quen" },
  { videoId: "NmahmPzRag8", title: "Cháo Trai - Vị Quê Nhà Trong Chiều Mưa Buông", slug: "chao-trai-vi-que-nha-trong-chieu-mua-buong" },
  { videoId: "lvVxggNty6w", title: "Gà rang gừng: Món ăn chưa bao giờ cũ", slug: "ga-rang-gung-mon-an-chua-bao-gio-cu" },
  { videoId: "8TSSS0uU7zQ", title: "Chả Ốc Lá Lốt | Hương Vị Quê Nhà Thơm Lừng Ngày Hè", slug: "cha-oc-la-lot-huong-vi-que-nha-thom-lung-ngay-he" },
  { videoId: "PniHo9J4OZs", title: "Mì Tôm Trộn Mực Trứng Gà: Ngon Khó Cưỡng, Đơn Giản Tại Nhà!", slug: "mi-tom-tron-muc-trung-ga-ngon-kho-cuong-don-gian-tai-nha" },
  { videoId: "H7PvXm26kQo", title: "Chè Đậu Xanh - Hương Vị Thanh Mát Gợi Nhớ Chiều Quê", slug: "che-dau-xanh-huong-vi-thanh-mat-goi-nho-chieu-que" },
  { videoId: "1dOdgmF-CJc", title: "Trứng Ngâm Tương | Món Ngon Vừa Tiện Vừa Đưa Cơm", slug: "trung-ngam-tuong-mon-ngon-vua-tien-vua-dua-com" },
  { videoId: "yNHcpX8b0ns", title: "Phở Xào Bò - Hương Vị Tuổi Thơ Thơm Lừng", slug: "pho-xao-bo-huong-vi-tuoi-tho-thom-lung" },
  { videoId: "3M0ayJqC_Yw", title: "Nộm Rau Muống Thịt Vịt | Vị Ngon Kéo Cả Nhà Đoàn Tụ", slug: "nom-rau-muong-thit-vit-vi-ngon-keo-ca-nha-doan-tu" },
  { videoId: "jmTz7BMT_u4", title: "Bún Bò Giò Heo | Vị Ngọt Thanh Nhẹ Giữa Chiều Đông", slug: "bun-bo-gio-heo-vi-ngot-thanh-nhe-giua-chieu-dong" },
  { videoId: "RO7xTUXMN-c", title: "Sốt Me Chua Ngọt - Bí Quyết Cho Món Ngon Vỉa Hè", slug: "sot-me-chua-ngot-bi-quyet-cho-mon-ngon-via-he" },
  { videoId: "L3mWO5gx-ys", title: "Tôm Rang Lá Chanh | Vị Quê Nhà Thơm Lừng Mâm Cơm", slug: "tom-rang-la-chanh-vi-que-nha-thom-lung-mam-com" },
  { videoId: "T9bJsozLHWc", title: "Cá Hồi Sốt Cam | Vị Chua Ngọt Thanh Mát Của Biển Cả", slug: "ca-hoi-sot-cam-vi-chua-ngot-thanh-mat-cua-bien-ca" },
  { videoId: "QXBM-cBHPr4", title: "Siro Mận | Thanh Mát Giải Nhiệt Giữa Trưa Hè", slug: "siro-man-thanh-mat-giai-nhiet-giua-trua-he" },
  { videoId: "HgfCTnNayA8", title: "Canh Mồng Tơi Nấu Gạch | Vị Thanh Mát Của Mùa Hè", slug: "canh-mong-toi-nau-gach-vi-thanh-mat-cua-mua-he" },
  { videoId: "DDhM4JJGxno", title: "Dứa Nướng Phô Mai Tôm Ngô - Vị Ngon Tan Chảy", slug: "dua-nuong-pho-mai-tom-ngo-vi-ngon-tan-chay" },
  { videoId: "m1dAl4JQhYY", title: "Chả Cá Lá Lốt - Vị Ngon Đậm Đà Nhớ Mãi Không Quên", slug: "cha-ca-la-lot-vi-ngon-dam-da-nho-mai-khong-quen" },
  { videoId: "VqQH4n8xg0g", title: "Muối Ớt Đỏ | Chấm Gì Cũng Ngon Tuyệt Hảo", slug: "muoi-ot-do-cham-gi-cung-ngon-tuyet-hao" },
  { videoId: "H0EC8ii_voA", title: "Tôm Hấp Bầu - Thanh Mát, Tinh Tế Hương Vị Quê Nhà", slug: "tom-hap-bau-thanh-mat-tinh-te-huong-vi-que-nha" },
  { videoId: "T5EBJ_m1Fzs", title: "Gỏi Bò Cà Pháo | Giòn Ngọt Chuẩn Vị Nhà Làm", slug: "goi-bo-ca-phao-gion-ngot-chuan-vi-nha-lam" },
  { videoId: "YVm944DQzSE", title: "Sườn Non Nấu Bí | Vị Ngọt Thơm Từ Tuổi Thơ", slug: "suon-non-nau-bi-vi-ngot-thom-tu-tuoi-tho" },
  { videoId: "-TudpncUjRM", title: "Cách làm Gà Rán KFC giòn rụm, thơm ngon tại nhà chỉ với 3 bước đơn giản!", slug: "cach-lam-ga-ran-kfc-gion-rum-thom-ngon-tai-nha-chi-voi-3-buoc-don-gian" },
  { videoId: "p5wAgf-E5W0", title: "Gà Ủ Muối - Hương Vị Tết Sum Vầy Trong Từng Miếng", slug: "ga-u-muoi-huong-vi-tet-sum-vay-trong-tung-mieng" },
  { videoId: "_snRjPGi160", title: "Sườn Kho Trứng Cút | Vị Ngọt Thanh Vị Khói Xa Xưa", slug: "suon-kho-trung-cut-vi-ngot-thanh-vi-khoi-xa-xua" },
  { videoId: "b4OkBv1uBZM", title: "Bún Thái Chay | Vị Chua Ngọt Thanh Mát Giữa Ngày Hè", slug: "bun-thai-chay-vi-chua-ngot-thanh-mat-giua-ngay-he" },
  { videoId: "UuAko-iGLvs", title: "Gà Xào Húng Quế | Mùi Thơm Của Mẹ Thoảng Qua Mái Nhà Xưa", slug: "ga-xao-hung-que-mui-thom-cua-me-thoang-qua-mai-nha-xua" },
  { videoId: "LdC-Ii3zqFk", title: "Canh Chua Đầu Cá | Vị Quê Nhà Gọi Về Những Chiều Mưa Nhớ", slug: "canh-chua-dau-ca-vi-que-nha-goi-ve-nhung-chieu-mua-nho" },
  { videoId: "n3qpL8uaLpo", title: "Canh Chua Sườn Heo | Vị Chua Ngọt Thanh Mát Ngày Hè", slug: "canh-chua-suon-heo-vi-chua-ngot-thanh-mat-ngay-he" },
  { videoId: "cLP28XlVm6E", title: "Ba Chỉ Kho Dưa Chua | Vị Chua Mặn Ấm Lòng Mẹ Nấu", slug: "ba-chi-kho-dua-chua-vi-chua-man-am-long-me-nau" },
  { videoId: "_Yc3VMOKBKM", title: "Chân Giò Hầm Táo - Vị Ngọt Thanh Của Mùa Xuân", slug: "chan-gio-ham-tao-vi-ngot-thanh-cua-mua-xuan" },
  { videoId: "fltik4I-arE", title: "Kho Quẹt Nồi Đất - Vị Ngon Về Nhà Tới Tấp", slug: "kho-quet-noi-dat-vi-ngon-ve-nha-toi-tap" },
  { videoId: "ZmkxbWm2x_c", title: "Chả Giò Ngô | Vị Giòn Tan Giữa Mùa Quê Yêu Thương", slug: "cha-gio-ngo-vi-gion-tan-giua-mua-que-yeu-thuong" },
  { videoId: "QV4O5pOPGi8", title: "Bún Thịt Nướng Bạch Tuộc | Món Ngon Nhớ Mãi Hương Vị Nhà", slug: "bun-thit-nuong-bach-tuoc-mon-ngon-nho-mai-huong-vi-nha" },
  { videoId: "DRBMG82zzao", title: "Cá Chiên Cuốn Rau | Vị Quê Thanh Thoát Giữa Phố Thị", slug: "ca-chien-cuon-rau-vi-que-thanh-thoat-giua-pho-thi" },
  { videoId: "xWOTf7CfUNw", title: "Lẩu Haidilao tại nhà trong vòng 30 phút", slug: "lau-haidilao-tai-nha-trong-vong-30-phut" },
  { videoId: "37m1dbWvJP8", title: "Món Canh Bổ Dương | Vị Quê Nhà Thanh Đạm Giữa Phố Thị", slug: "mon-canh-bo-duong-vi-que-nha-thanh-dam-giua-pho-thi" },
  { videoId: "3jDb8TF0F-Q", title: "Cánh Gà Rang Muối | Giòn Rụm Vị Quê Nhà Trên Mâm Cơm", slug: "canh-ga-rang-muoi-gion-rum-vi-que-nha-tren-mam-com-2" },
  { videoId: "UOROWjN6WKI", title: "Bánh Đa Cá: Món Ngon Dễ Làm, Chuẩn Vị Quê Nhà", slug: "banh-da-ca-mon-ngon-de-lam-chuan-vi-que-nha" },
  { videoId: "WrmCagTDT5I", title: "Bánh hẹ - Món Bánh Tuổi Thơ Của Mẹ", slug: "banh-he-mon-banh-tuoi-tho-cua-me" },
  { videoId: "ikyiLx_N_e8", title: "Cá Hấp Đinh Lăng - Hương Vị Truyền Thống Ấm Áp", slug: "ca-hap-dinh-lang-huong-vi-truyen-thong-am-ap" },
  { videoId: "7BO57eMFMGQ", title: "Miến Húng Quế - Hương Vị Như Mâm Cơm Mẹ Nấu", slug: "mien-hung-que-huong-vi-nhu-mam-com-me-nau" },
  { videoId: "YE_Bie83qRw", title: "Bò Kho Bánh Mỳ - Ấm Áp Hương Vị Quê Nhà", slug: "bo-kho-banh-my-am-ap-huong-vi-que-nha" },
  { videoId: "2cT9qIiy3c8", title: "Gỏi Gà Xé Phay | Thanh Mát Ngày Hè, Vị Ngon Khó Cưỡng", slug: "goi-ga-xe-phay-thanh-mat-ngay-he-vi-ngon-kho-cuong" },
  { videoId: "hkfNx2_vgYU", title: "Cách làm Ốc Luộc Sả Ớt và Sung Muối Chua Ngọt ăn là ghiền", slug: "cach-lam-oc-luoc-sa-ot-va-sung-muoi-chua-ngot-an-la-ghien" },
  { videoId: "e8gsZ-rDI98", title: "Bò Kho | Hương Vị Quê Nhà Ấm Áp Cho Ngày Đông Lạnh", slug: "bo-kho-huong-vi-que-nha-am-ap-cho-ngay-dong-lanh" },
  { videoId: "BSRlutsEp9A", title: "Kem Xoài - Mát Lạnh Tan Chảy Ngày Hè", slug: "kem-xoai-mat-lanh-tan-chay-ngay-he" },
  { videoId: "YkZMGNAmgTY", title: "Trứng Gà Nướng | Vị Ngon Thơ Bé Theo Tôi Cả Cuộc Đời", slug: "trung-ga-nuong-vi-ngon-tho-be-theo-toi-ca-cuoc-doi" },
  { videoId: "PlmLZztma5g", title: "[Góc chi tiết] Bí quyết Xôi Mặn Miền Nam: Hạt xôi bóng mượt, dẻo thơm không bị nát 🍚✨", slug: "goc-chi-tiet-bi-quyet-xoi-man-mien-nam-hat-xoi-bong-muot-deo-thom-khon" },
  { videoId: "pIWk5tN5e_I", title: "Tôm Rang Thịt Ba Chỉ | Hương Vị Quê Nhà Gọi Bữa Cơm Chiều", slug: "tom-rang-thit-ba-chi-huong-vi-que-nha-goi-bua-com-chieu-2" },
  { videoId: "5BXaFJkhnlI", title: "Bò Hầm Rau Củ | Vị Ngọt Dịu Của Những Chiều Mưa Nhớ Nhà", slug: "bo-ham-rau-cu-vi-ngot-diu-cua-nhung-chieu-mua-nho-nha" },
  { videoId: "no2xktxsAsY", title: "Tôm rim mặn ngọt thơm ngon, cách làm đơn giản tại nhà", slug: "tom-rim-man-ngot-thom-ngon-cach-lam-don-gian-tai-nha" },
  { videoId: "8-Ifj7tEDF4", title: "Yến Mạch Ngâm Qua Đêm | Bữa Sáng Ngon Lành Cho Ngày Dài Năng Động", slug: "yen-mach-ngam-qua-dem-bua-sang-ngon-lanh-cho-ngay-dai-nang-dong" },
  { videoId: "-zPtGc_wrPA", title: "Bánh Mỳ Phomai - Vị Béo Ngậy Tan Chảy Cùng Tiếng Vụn Vặt Giòn Tan", slug: "banh-my-phomai-vi-beo-ngay-tan-chay-cung-tieng-vun-vat-gion-tan" },
  { videoId: "1kjMYePj89I", title: "Bò Nấu Mẻ | Vị Chua Thanh Làm Ấm Lòng Ngày Lạnh", slug: "bo-nau-me-vi-chua-thanh-lam-am-long-ngay-lanh" },
  { videoId: "Yz2jko4_sK4", title: "Trứng cá chiên lá lốt, món lạ cực bén", slug: "trung-ca-chien-la-lot-mon-la-cuc-ben" },
  { videoId: "cz2PDjq-lpQ", title: "Nem Tai Heo Trộn Thính - Món Được Mẹ Chồng Truyền Lại Để Em Giữ Chồng", slug: "nem-tai-heo-tron-thinh-mon-duoc-me-chong-truyen-lai-de-em-giu-chong" },
  { videoId: "4TVKYrrgmaQ", title: "Tháp Sườn Cay Thái Lan | Hương Vị Cay Nồng Thơm Lừng Gọi Nhớ", slug: "thap-suon-cay-thai-lan-huong-vi-cay-nong-thom-lung-goi-nho" },
  { videoId: "pHcKrQyWV8I", title: "Bánh Khoai Lang Phô Mai - Chiếc Bánh Ấm Áp Cho Ngày Dài", slug: "banh-khoai-lang-pho-mai-chiec-banh-am-ap-cho-ngay-dai" },
  { videoId: "OYyWSHBanIw", title: "Bún Cá Rô Chiên | Hương Vị Thân Thương", slug: "bun-ca-ro-chien-huong-vi-than-thuong" },
  { videoId: "jt8rI2EQAl4", title: "Chân Gà Ngâm Xã Tắc - Vị Chua Cay Ngon Nuốc Lưỡi", slug: "chan-ga-ngam-xa-tac-vi-chua-cay-ngon-nuoc-luoi" },
  { videoId: "Tvy3FMIFHnk", title: "Bún Đầu Cá Nấu Su Hào - Vị Ngọt Thanh Thoát Của Mùa Hè Nóng Bức", slug: "bun-dau-ca-nau-su-hao-vi-ngot-thanh-thoat-cua-mua-he-nong-buc" },
  { videoId: "XRQDelrte8Q", title: "[Góc chi tiết] Mì Hoành Thánh - Chuẩn vị của người Hoa", slug: "goc-chi-tiet-mi-hoanh-thanh-chuan-vi-cua-nguoi-hoa" },
  { videoId: "Nf6yAqTXnwg", title: "Hết nồi cơm với món này", slug: "het-noi-com-voi-mon-nay" },
  { videoId: "GJgkueQXr2o", title: "Đậu Phụ Tẩm Hành | Món Ngon Dễ Làm Mùi Thơm Quyến Rũ", slug: "dau-phu-tam-hanh-mon-ngon-de-lam-mui-thom-quyen-ru" },
  { videoId: "xpxnu6KCtGc", title: "Bánh Mì Nướng Bơ Tỏi Ngô Phô Mai - Mùi Thơm Tan Chảy Cuốn Hút", slug: "banh-mi-nuong-bo-toi-ngo-pho-mai-mui-thom-tan-chay-cuon-hut-2" },
  { videoId: "il8aUMONucc", title: "Bún Cá - Cái Mùi Mẻ Không Thể Quên", slug: "bun-ca-cai-mui-me-khong-the-quen" },
  { videoId: "tSry1XHy-UE", title: "Bánh Khoai Mỡ Phomai Kéo Sợi | Món ngon cho đội nghỉ hè", slug: "banh-khoai-mo-phomai-keo-soi-mon-ngon-cho-doi-nghi-he" },
  { videoId: "Vju1IfCX8Ug", title: "Bún Mọc - Ngọt thanh", slug: "bun-moc-ngot-thanh" },
  { videoId: "_Wzny9eZBIs", title: "Nụ Bí Xào Bò | Món Quà Quê Thanh Mát, Dễ Làm", slug: "nu-bi-xao-bo-mon-qua-que-thanh-mat-de-lam" },
  { videoId: "DMMbaIsvzEI", title: "Củ Sen Hầm Xương - Món Quà Ấm Áp Từ Gian Bếp", slug: "cu-sen-ham-xuong-mon-qua-am-ap-tu-gian-bep" },
  { videoId: "L2kyrM9Xxd8", title: "Xôi Hoa Đậu Biếc - Hương Vị Tuổi Thơ Bình Yên", slug: "xoi-hoa-dau-biec-huong-vi-tuoi-tho-binh-yen" },
  { videoId: "41UPErjx-lw", title: "Mì Hoành Thánh Thịt Bò | Ấm Lòng Ngày Se Lạnh", slug: "mi-hoanh-thanh-thit-bo-am-long-ngay-se-lanh" },
  { videoId: "px93Kdcc3Xg", title: "Bánh Cuốn Nóng Không Cần Tráng | Hương Vị Ấm Áp Ngày Se Lạnh", slug: "banh-cuon-nong-khong-can-trang-huong-vi-am-ap-ngay-se-lanh" },
  { videoId: "IqBujbuNPw8", title: "Gà Ác Hầm Thuốc Bắc | Bổ Dưỡng Ngon Tuyệt Cho Cả Nhà", slug: "ga-ac-ham-thuoc-bac-bo-duong-ngon-tuyet-cho-ca-nha" },
  { videoId: "ktceDo12Vek", title: "Thịt Kho Dừa - Ấm Áp Cả Nhà Về Mâm Cơm Chiều", slug: "thit-kho-dua-am-ap-ca-nha-ve-mam-com-chieu" },
  { videoId: "ahUOpTRwb1g", title: "Sườn Rim Dứa | Món Ngon Ấm Áp Cho Bữa Cơm Gia Đình", slug: "suon-rim-dua-mon-ngon-am-ap-cho-bua-com-gia-dinh" },
  { videoId: "G_fz_avE0to", title: "Bò Cháy Tỏi Sốt Tiêu Xanh - Hương Vị Cổ Điển Trở Về", slug: "bo-chay-toi-sot-tieu-xanh-huong-vi-co-dien-tro-ve" },
  { videoId: "_qkXDtXNY5s", title: "Thịt Xá Xíu | Món Ngon Chuẩn Vị Mẹ Nấu", slug: "thit-xa-xiu-mon-ngon-chuan-vi-me-nau" },
  { videoId: "F-lTR0x6-bA", title: "Bún Cá | Vị Chua Thanh Của Mùa Hè Trong Nồi Nước Dùng Ấm Áp", slug: "bun-ca-vi-chua-thanh-cua-mua-he-trong-noi-nuoc-dung-am-ap" },
  { videoId: "DpArkd_dNgs", title: "Tôm Rang Me Chua Ngọt | Vị Quê Nhà Trong Bữa Cơm Gia Đình", slug: "tom-rang-me-chua-ngot-vi-que-nha-trong-bua-com-gia-dinh" },
  { videoId: "P998lyZlW4s", title: "Mực Nấu Chua Cay | Vị Quê Nhà Trong Bữa Cơm Thời Hiện Đại", slug: "muc-nau-chua-cay-vi-que-nha-trong-bua-com-thoi-hien-dai" },
  { videoId: "QkTQMueBPS4", title: "Bò Xào Cà Pháo Lá Lốt - Mùi Thơm Vương Vấn Khó Cưỡng", slug: "bo-xao-ca-phao-la-lot-mui-thom-vuong-van-kho-cuong" },
  { videoId: "oLRDWtZSy4Y", title: "Lẩu gà nước dừa mới lạ", slug: "lau-ga-nuoc-dua-moi-la" },
  { videoId: "OwKorpWsxew", title: "Bún Cá Chấm Giòn | Món Ngon Cuốn Hút Vị Quê Nhà", slug: "bun-ca-cham-gion-mon-ngon-cuon-hut-vi-que-nha" },
  { videoId: "S5bQYdJv9qo", title: "Lòng Mề Gà Xào Đậu Que - Mùi Thơm Lừng Gọi Cả Chiều Về", slug: "long-me-ga-xao-dau-que-mui-thom-lung-goi-ca-chieu-ve" },
  { videoId: "9lPZ2LyGd8w", title: "[Góc chi tiết] Nồi Xá Xíu Này Nhìn Là Muốn Ăn Ngay! 🔥", slug: "goc-chi-tiet-noi-xa-xiu-nay-nhin-la-muon-an-ngay" },
  { videoId: "k3I0u5dl53U", title: "Gà Rán Giòn Rụm | Hương Vị Tuổi Thơ Thơm Lừng Căn Bếp", slug: "ga-ran-gion-rum-huong-vi-tuoi-tho-thom-lung-can-bep" },
  { videoId: "UKjdxeSQK84", title: "Đậu Hũ Lắc Sate - Cay Thơm Lạ Miệng Ngày Mưa", slug: "dau-hu-lac-sate-cay-thom-la-mieng-ngay-mua" },
  { videoId: "4QKr0J3o2xE", title: "Nui Xào Bò | Món Ngon Nhanh Gọn Cho Bữa Tối", slug: "nui-xao-bo-mon-ngon-nhanh-gon-cho-bua-toi" },
  { videoId: "PjTDdRbG4-Q", title: "Bao Tử Hầm | Nấu Món Quê Giữa Lòng Phố Thị", slug: "bao-tu-ham-nau-mon-que-giua-long-pho-thi" },
  { videoId: "vJv7u-ROY_8", title: "Canh Chua Cá Nấu Khế | Vị Quê Nhà Bay Vào Bếp Hiện Đại", slug: "canh-chua-ca-nau-khe-vi-que-nha-bay-vao-bep-hien-dai" },
  { videoId: "_zSVMlaMvTs", title: "Canh Trứng Nấm | Món Ngon Dễ Làm Cho Mọi Nhà", slug: "canh-trung-nam-mon-ngon-de-lam-cho-moi-nha" },
  { videoId: "oi-42YxAhV8", title: "Nghêu Sốt Phô Mai Trứng Muối | Món Ngon Đơn Giản Đậm Đà", slug: "ngheu-sot-pho-mai-trung-muoi-mon-ngon-don-gian-dam-da" },
  { videoId: "4GsvZ2Z55zY", title: "Bánh cuốn lười, ai cũng tự làm được", slug: "banh-cuon-luoi-ai-cung-tu-lam-duoc" },
  { videoId: "IxhBQPFAOj0", title: "Ngô Chiên Giòn | Món Ăn Vặt Nhỏ Xíu Cho Ngày Dài Thêm Vui", slug: "ngo-chien-gion-mon-an-vat-nho-xiu-cho-ngay-dai-them-vui" },
  { videoId: "v_-_qPqeGvc", title: "Ăn mì mà vẫn giảm cân? Thử ngay Mì Soba Gà Nấm 🍜", slug: "an-mi-ma-van-giam-can-thu-ngay-mi-soba-ga-nam" },
  { videoId: "C9I-1kdNktQ", title: "Ếch rang muối, món cực kỳ hao bia", slug: "ech-rang-muoi-mon-cuc-ky-hao-bia" },
  { videoId: "d2Qk5N1koNE", title: "[Góc chi tiết] Bùn Bò Huế Chay | Thanh đạm - Đậm đà", slug: "goc-chi-tiet-bun-bo-hue-chay-thanh-dam-dam-da" },
  { videoId: "qc8kNwUUpQg", title: "Sườn Rim Dứa | Món Ngon Mùa Hè Chua Ngọt Đậm Đà", slug: "suon-rim-dua-mon-ngon-mua-he-chua-ngot-dam-da" },
  { videoId: "jxRZgWC19PA", title: "Tự làm bánh cuốn tại nhà với bánh tráng cuốn chả giò siu đơn giản", slug: "tu-lam-banh-cuon-tai-nha-voi-banh-trang-cuon-cha-gio-siu-don-gian" },
  { videoId: "OJvhXzbB9lc", title: "Cơm Chiên Gà Xé Tỏi | Món Ngon Cả Nhà Đều Mê", slug: "com-chien-ga-xe-toi-mon-ngon-ca-nha-deu-me" },
  { videoId: "LuiQ_neNwuA", title: "Canh Khổ Qua Nhồi Thịt | Vị Đắng Thanh Mát Cho Bữa Cơm Gia Đình", slug: "canh-kho-qua-nhoi-thit-vi-dang-thanh-mat-cho-bua-com-gia-dinh" },
];
